"""add t_order.user_id FK

Revision ID: cad8a3b29f3a
Revises: 6fd39b4d038f
Create Date: 2026-06-09 15:01:10.471816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad8a3b29f3a'
down_revision: Union[str, Sequence[str], None] = '6fd39b4d038f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_order', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_t_order_user_id'), 't_order', ['user_id'], unique=False)
    op.create_foreign_key(None, 't_order', 't_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_order', type_='foreignkey')
    op.drop_index(op.f('ix_t_order_user_id'), table_name='t_order')
    op.drop_column('t_order', 'user_id')
    # ### end Alembic commands ###
